### ISSUE TITLE
Two part front frame

### ISSUE THREAD

**Issue by kontakt** [jdoscher/Back7co-ARM-Terminal#1]
I'm looking forward to building this, and I ordered the bits that go inside. When I went to print, I realized that the front frame does not fit on my Ender 3's bed. I see you have a A/B rear frame, would it be possible to have the front frame split as well?

**Comment by jdoscher** [comment]
I'm glad to hear you're building it, but the front frame is where all the rigidity comes from.  Without a single component, the design would put too much force on the inner frame that the LCD mounts to, and necessitate a redesign there as well.  The parts were designed in Tinkercad, so if you're up to the challenge feel free to take a pass at a design and follow up here.  They are on Tinkercad at https://www.tinkercad.com/things/78rksgc3iAu-back7co-arm-terminal/edit and can be "ungrouped" and modified there.  Thanks!

**Comment by kontakt** [comment]
I downloaded the STLs and sliced them in Fusion 360, I just did a Z-shaped cut over the center hole and I intend to bond them with heated inserts. I'll upload the files and make a PR if the results are good.

**Comment by kontakt** [comment]
Results are positive, with a bit of glue and a bolt, the structure feels pretty sturdy.
